title: Fabio Gorodscy github page
email: fabiogo@outlook.com
description: This is Fabio Gorodscy bio page and blog. I try to keep it updated with 
  new things I learn through my life.
github_username:  fabiogoro
url: http://fabiogoro.github.io
author: Fabio Gorodscy

permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-seo-tag
