title: my github page
email: fabiogo@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is my bio page and blog. I'll try to keep it updated with 
  new things I learn through my life.
github_username:  fabiogoro

# markdown: kramdown

permalink: /blog/:year/:month/:day/:title
